# Ruby CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-ruby/ for more details

version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
       - image: circleci/ruby:2.4.1-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "84:b8:1c:87:23:48:84:15:b7:64:d9:10:dd:db:c6:ed"

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            bundle install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Build static website
          command: |
              ./scripts/build.sh

      - run:
          name: Configure git user info
          command: |
              git config --global user.email "eduardogarcia.xyz+gh@gmail.com"
              git config --global user.name "Eduardo Garcia"

      - run:
          name: Deploy static website
          command: |
              ./scripts/publish.sh
